### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Xuacu** [edewaele/nomino#8] opened 2014-09-09 00:50 UTC
When I try to log in, authentication process seems to try to log onto www.openstreetmap.orgh (please, note the trailing «h»)
It seems to happen today, yesterday It worked just fine.
Best regards.

**Comment by stefanb** [comment] 2014-09-11 20:32
This URL probably needs to be fixed in the Nomino application OAuth settings on the www.openstreetmap.org

**Comment by stefanb** [comment] 2014-09-11 20:33
Workaround: replace " www.openstreetmap.orgh" in the URL with "nomino.openstreetmap.fr", leaving the OAuth parameters in the URL

**Comment by edewaele** [comment] 2014-09-12 18:53
The OAuth settings seem to be correct.

I could not reproduce this issue.

**Comment by stefanb** [comment] 2014-09-12 19:25
I noticed it worked fine earlier today & thought you fixed the settings.

**Comment by Xuacu** [comment] 2014-09-12 21:46
It works fine now for me. Thank you all.

**Closed as completed** 2014-09-12 21:48 UTC
